name: 'Security Audit'
description: 'Run security audit with known CVE exceptions'

runs:
  using: 'composite'
  steps:
    - name: 🔍 Run security audit
      shell: bash
      run: |
        # 临时切换到官方 registry 进行 audit
        pnpm config set registry https://registry.npmjs.org

        echo "🔍 Running security audit with known CVE exceptions..."
        echo "📋 Ignoring xlsx CVEs: CVE-2024-22363, GHSA-4r6h-8v6p-xvw6, GHSA-5pgg-2g8v-p4x9"
        echo "💡 Reason: Low risk in our controlled environment - only parsing user-uploaded files with size limits"

        # 运行 audit 并获取结果
        audit_exit_code=0
        pnpm audit --audit-level moderate --json > audit-results.json || audit_exit_code=$?

        # 检查 audit 结果
        if [ -f "audit-results.json" ] && [ -s "audit-results.json" ]; then
          echo "📋 Audit results found, analyzing..."

          # 检查是否有漏洞数据
          vulnerabilities_count=$(cat audit-results.json | jq -r '.metadata.vulnerabilities.total // 0' 2>/dev/null || echo "0")

          if [ "$vulnerabilities_count" -gt 0 ]; then
            echo "⚠️ Found $vulnerabilities_count vulnerabilities, filtering known exceptions..."

            # 提取漏洞信息并过滤掉已知的 xlsx 漏洞
            cat audit-results.json | jq -r '
              .vulnerabilities // {} |
              to_entries[] |
              select(.value.via[0].source // .value.via[0] |
                test("CVE-2024-22363|GHSA-4r6h-8v6p-xvw6|GHSA-5pgg-2g8v-p4x9") | not
              ) |
              .value
            ' > filtered-vulnerabilities.json 2>/dev/null || echo "[]" > filtered-vulnerabilities.json

            # 检查过滤后是否还有漏洞
            if [ -s "filtered-vulnerabilities.json" ] && [ "$(cat filtered-vulnerabilities.json | jq -r '. | length' 2>/dev/null || echo "0")" -gt 0 ]; then
              echo "❌ Found security vulnerabilities after filtering:"
              cat filtered-vulnerabilities.json | jq -r '.' 2>/dev/null || cat filtered-vulnerabilities.json
              exit 1
            else
              echo "✅ All vulnerabilities are in the known exceptions list"
            fi
          else
            echo "✅ No security vulnerabilities found"
          fi
        else
          if [ $audit_exit_code -eq 0 ]; then
            echo "✅ No security vulnerabilities found"
          else
            echo "⚠️ Audit command failed but no results file generated, treating as no vulnerabilities"
          fi
        fi

    - name: 🔄 Restore registry config
      if: always()
      shell: bash
      run: |
        # 恢复原始 registry 配置
        pnpm config set registry https://registry.npmmirror.com
