version: '3.8'

services:
  # 测试 PostgreSQL 数据库
  postgres-test:
    image: postgres:15-alpine
    container_name: yun-todolist-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: yun_ai_todolist_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - todolist-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yun_ai_todolist_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 测试 Redis 缓存
  redis-test:
    image: redis:7-alpine
    container_name: yun-todolist-redis-test
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6381:6379"
    volumes:
      - redis_test_data:/data
    networks:
      - todolist-test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  todolist-test-network:
    driver: bridge
    name: yun-todolist-test-network

volumes:
  postgres_test_data:
    name: yun-todolist-postgres-test-data
  redis_test_data:
    name: yun-todolist-redis-test-data
