name = "yun-ai-todolist"
main = "workers-site/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# 全局环境变量
[vars]
ENVIRONMENT = "production"
APP_NAME = "Yun AI TodoList"
APP_VERSION = "1.0.0"

# Workers Assets 配置
[assets]
directory = "./apps/frontend/dist"
serve_single_page_app = true
html_handling = "auto-trailing-slash"
text_compression = "gzip"

# 统一部署配置
# 所有环境变量在这里配置

# KV 存储配置（如果需要）
# [[kv_namespaces]]
# binding = "TODO_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 数据库配置（如果需要）
# [[d1_databases]]
# binding = "DB"
# database_name = "todo-db"
# database_id = "your-database-id"

# 自定义域名配置
# [env.production.routes]
# pattern = "todo.yourdomain.com/*"
# zone_name = "yourdomain.com"
