name = "yun-ai-todolist"
main = "workers-site/index.js"
compatibility_date = "2024-06-18"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
ENVIRONMENT = "production"

# Workers Assets 配置
[assets]
directory = "./apps/frontend/dist"
serve_single_page_app = true

# 开发环境配置
[env.development]
name = "yun-ai-todolist-dev"
vars = { ENVIRONMENT = "development" }

# 生产环境配置
[env.production]
name = "yun-ai-todolist-prod"
vars = { ENVIRONMENT = "production" }

# KV 存储配置（如果需要）
# [[kv_namespaces]]
# binding = "TODO_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 数据库配置（如果需要）
# [[d1_databases]]
# binding = "DB"
# database_name = "todo-db"
# database_id = "your-database-id"

# 自定义域名配置
# [env.production.routes]
# pattern = "todo.yourdomain.com/*"
# zone_name = "yourdomain.com"
