import js from '@eslint/js'
import typescript from '@typescript-eslint/eslint-plugin'
import typescriptParser from '@typescript-eslint/parser'
import prettier from 'eslint-config-prettier'
import vue from 'eslint-plugin-vue'
import vueParser from 'vue-eslint-parser'

export default [
  {
    ignores: [
      'dist/**',
      'dev-dist/**',
      'node_modules/**',
      'coverage/**',
      'coverage/**/*.js',
      'coverage/**/*.html',
      'coverage/**/*.css',
      'release/**',
      '*.min.js',
      'public/**',
      'public/pdf.worker.min.mjs',
      '.husky/**',
      '**/prettify.js',
      '**/sorter.js',
      '**/block-navigation.js',
      'auto-imports.d.ts',
      'src/types/pwa.d.ts',
      'vite.config.ts',
      'uno.config.ts',
      '**/workbox-*.js',
      '**/sw.js',
      'eslint.config.js',
    ],
  },

  js.configs.recommended,

  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        __VUE_I18N_LEGACY_API__: 'readonly',
        __VUE_I18N_FULL_INSTALL__: 'readonly',
        __INTLIFY_PROD_DEVTOOLS__: 'readonly',

        // DOM types
        Document: 'readonly',
        Window: 'readonly',
        DocumentEventMap: 'readonly',
        WindowEventMap: 'readonly',
        AddEventListenerOptions: 'readonly',
        EventTarget: 'readonly',
        EventListener: 'readonly',
        ErrorEvent: 'readonly',
        PromiseRejectionEvent: 'readonly',

        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        Navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        console: 'readonly',

        fetch: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        AbortController: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        performance: 'readonly',
        Performance: 'readonly',
        PerformanceEntry: 'readonly',
        PerformanceNavigationTiming: 'readonly',
        confirm: 'readonly',
        alert: 'readonly',

        Event: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        MessageEvent: 'readonly',
        MediaQueryListEvent: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLButtonElement: 'readonly',

        Notification: 'readonly',
        SpeechRecognition: 'readonly',
        webkitSpeechRecognition: 'readonly',
        SpeechRecognitionResultList: 'readonly',

        RouteLocationNormalized: 'readonly',
        NavigationGuardNext: 'readonly',

        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',

        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',

        Worker: 'readonly',
        ResizeObserver: 'readonly',
        PerformanceObserver: 'readonly',
        FormData: 'readonly',

        // Vue 3 Composition API
        ref: 'readonly',
        reactive: 'readonly',
        computed: 'readonly',
        watch: 'readonly',
        watchEffect: 'readonly',
        onMounted: 'readonly',
        onUnmounted: 'readonly',
        onBeforeMount: 'readonly',
        onBeforeUnmount: 'readonly',
        onUpdated: 'readonly',
        onBeforeUpdate: 'readonly',
        onActivated: 'readonly',
        onDeactivated: 'readonly',
        onErrorCaptured: 'readonly',
        nextTick: 'readonly',
        provide: 'readonly',
        inject: 'readonly',
        defineComponent: 'readonly',
        defineAsyncComponent: 'readonly',
        createApp: 'readonly',
        h: 'readonly',
        toRef: 'readonly',
        toRefs: 'readonly',
        unref: 'readonly',
        isRef: 'readonly',
        isReactive: 'readonly',
        isReadonly: 'readonly',
        isProxy: 'readonly',
        markRaw: 'readonly',
        shallowRef: 'readonly',
        shallowReactive: 'readonly',
        shallowReadonly: 'readonly',
        readonly: 'readonly',
        customRef: 'readonly',
        triggerRef: 'readonly',
        toRaw: 'readonly',
        effectScope: 'readonly',
        getCurrentScope: 'readonly',
        onScopeDispose: 'readonly',
        getCurrentInstance: 'readonly',
        useAttrs: 'readonly',
        useSlots: 'readonly',
        useCssModule: 'readonly',
        useCssVars: 'readonly',

        useRouter: 'readonly',
        useRoute: 'readonly',
        onBeforeRouteLeave: 'readonly',
        onBeforeRouteUpdate: 'readonly',

        useI18n: 'readonly',

        useWindowSize: 'readonly',
        useMouse: 'readonly',
        useLocalStorage: 'readonly',
        useSessionStorage: 'readonly',
        useClipboard: 'readonly',
        useEventListener: 'readonly',
        useDark: 'readonly',
        useColorMode: 'readonly',
        useToggle: 'readonly',
        useCounter: 'readonly',
        useDebounce: 'readonly',
        useDebounceFn: 'readonly',
        useThrottle: 'readonly',
        useThrottleFn: 'readonly',
        useInterval: 'readonly',
        useTimeout: 'readonly',
        useNow: 'readonly',
        useTimestamp: 'readonly',
        useMounted: 'readonly',
        useElementSize: 'readonly',
        useElementVisibility: 'readonly',
        useIntersectionObserver: 'readonly',
        useResizeObserver: 'readonly',
        useMutationObserver: 'readonly',
        useMediaQuery: 'readonly',
        useBreakpoints: 'readonly',
        useOnline: 'readonly',
        useNetwork: 'readonly',
        useFetch: 'readonly',
        useAsyncState: 'readonly',

        // PWA 相关全局变量
        caches: 'readonly',

        // 浏览器 API
        atob: 'readonly',
        btoa: 'readonly',
        CustomEvent: 'readonly',
        HTMLAnchorElement: 'readonly',
        Node: 'readonly',
        AbortSignal: 'readonly',
        RequestInit: 'readonly',

        // Token Manager
        tokenManager: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': typescript,
    },
    rules: {
      'no-console':
        process.env.NODE_ENV === 'production'
          ? ['error', { allow: ['warn', 'error', 'group', 'groupEnd'] }]
          : 'off',
      'no-debugger': 'error',
      'no-unused-vars': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-func-assign': 'error',
      'no-constant-condition': 'error',
      'no-cond-assign': 'error',
      'no-case-declarations': 'off',

      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern:
            '^_|^(emit|router|canSync|formatTime|addTodo|updateTodo|deleteTodo|user|mockTodos|generateUUID|localTexts|serverTexts)$',
          caughtErrorsIgnorePattern: '^_|^error$',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      '@typescript-eslint/ban-types': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',

      'prefer-const': 'error',
      'no-var': 'error',
      eqeqeq: ['error', 'always'],
      curly: ['error', 'all'],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
    },
  },

  ...vue.configs['flat/recommended'],
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: typescriptParser,
        ecmaVersion: 'latest',
        sourceType: 'module',
        extraFileExtensions: ['.vue'],
      },
      globals: {
        __VUE_I18N_LEGACY_API__: 'readonly',
        __VUE_I18N_FULL_INSTALL__: 'readonly',
        __INTLIFY_PROD_DEVTOOLS__: 'readonly',

        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        console: 'readonly',

        fetch: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        AbortController: 'readonly',
        TextDecoder: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        performance: 'readonly',
        Performance: 'readonly',
        PerformanceEntry: 'readonly',
        PerformanceNavigationTiming: 'readonly',
        confirm: 'readonly',
        alert: 'readonly',

        Event: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        MessageEvent: 'readonly',
        MediaQueryListEvent: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLDivElement: 'readonly',
        EventTarget: 'readonly',

        Notification: 'readonly',
        SpeechRecognition: 'readonly',
        webkitSpeechRecognition: 'readonly',
        SpeechRecognitionResultList: 'readonly',

        RouteLocationNormalized: 'readonly',
        NavigationGuardNext: 'readonly',

        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',

        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',
        FormData: 'readonly',

        Worker: 'readonly',
        ResizeObserver: 'readonly',
        PerformanceObserver: 'readonly',

        ref: 'readonly',
        reactive: 'readonly',
        computed: 'readonly',
        watch: 'readonly',
        watchEffect: 'readonly',
        onMounted: 'readonly',
        onUnmounted: 'readonly',
        onBeforeMount: 'readonly',
        onBeforeUnmount: 'readonly',
        onUpdated: 'readonly',
        onBeforeUpdate: 'readonly',
        onActivated: 'readonly',
        onDeactivated: 'readonly',
        onErrorCaptured: 'readonly',
        nextTick: 'readonly',
        provide: 'readonly',
        inject: 'readonly',
        defineComponent: 'readonly',
        defineAsyncComponent: 'readonly',
        h: 'readonly',
        toRef: 'readonly',
        toRefs: 'readonly',
        unref: 'readonly',
        isRef: 'readonly',
        isReactive: 'readonly',
        isReadonly: 'readonly',
        isProxy: 'readonly',
        markRaw: 'readonly',
        shallowRef: 'readonly',
        shallowReactive: 'readonly',
        shallowReadonly: 'readonly',
        readonly: 'readonly',
        customRef: 'readonly',
        triggerRef: 'readonly',
        toRaw: 'readonly',
        effectScope: 'readonly',
        getCurrentScope: 'readonly',
        onScopeDispose: 'readonly',
        getCurrentInstance: 'readonly',
        useAttrs: 'readonly',
        useSlots: 'readonly',
        useCssModule: 'readonly',
        useCssVars: 'readonly',

        useRouter: 'readonly',
        useRoute: 'readonly',
        onBeforeRouteLeave: 'readonly',
        onBeforeRouteUpdate: 'readonly',

        useI18n: 'readonly',

        useWindowSize: 'readonly',
        useMouse: 'readonly',
        useLocalStorage: 'readonly',
        useSessionStorage: 'readonly',
        useClipboard: 'readonly',
        useEventListener: 'readonly',
        useDark: 'readonly',
        useColorMode: 'readonly',
        useToggle: 'readonly',
        useCounter: 'readonly',
        useDebounce: 'readonly',
        useDebounceFn: 'readonly',
        useThrottle: 'readonly',
        useThrottleFn: 'readonly',
        useInterval: 'readonly',
        useTimeout: 'readonly',
        useNow: 'readonly',
        useTimestamp: 'readonly',
        useMounted: 'readonly',
        useElementSize: 'readonly',
        useElementVisibility: 'readonly',
        useIntersectionObserver: 'readonly',
        useResizeObserver: 'readonly',
        useMutationObserver: 'readonly',
        useMediaQuery: 'readonly',
        useBreakpoints: 'readonly',
        useOnline: 'readonly',
        useNetwork: 'readonly',
        useFetch: 'readonly',
        useAsyncState: 'readonly',

        // PWA 相关全局变量
        caches: 'readonly',

        // 浏览器 API
        atob: 'readonly',
        btoa: 'readonly',
        CustomEvent: 'readonly',
        HTMLAnchorElement: 'readonly',
        Node: 'readonly',
        AbortSignal: 'readonly',
        RequestInit: 'readonly',

        // Token Manager
        tokenManager: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': typescript,
      vue,
    },
    rules: {
      'vue/no-v-html': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/no-multiple-template-root': 'off',

      'no-console': ['warn', { allow: ['error', 'warn'] }],
      'no-debugger': 'warn',
      'no-unused-vars': 'off',

      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-non-null-assertion': 'warn',

      'prefer-const': 'error',
      'no-var': 'error',
      eqeqeq: ['error', 'always'],
      curly: ['error', 'all'],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
    },
  },

  {
    files: [
      '**/workers/**/*.ts',
      '**/worker*.ts',
      'src/workers/**/*.ts',
      '**/sw.js',
      '**/service-worker.js',
    ],
    languageOptions: {
      globals: {
        self: 'readonly',
        caches: 'readonly',
        importScripts: 'readonly',
        postMessage: 'readonly',
        onmessage: 'readonly',
        addEventListener: 'readonly',
        removeEventListener: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',
        URL: 'readonly',
        clients: 'readonly',
        registration: 'readonly',
        skipWaiting: 'readonly',
      },
    },
  },

  {
    files: ['*.config.js', '*.config.ts', 'vite.config.ts', 'vitest.config.ts'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-var-requires': 'off',
    },
  },

  {
    files: [
      'electron/**/*.js',
      'scripts/**/*.js',
      'scripts/**/*.mjs',
      '*.config.js',
      '*.config.mjs',
    ],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',

        electron: 'readonly',

        URL: 'readonly',
        URLSearchParams: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        AbortController: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      'no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  {
    files: ['**/*.test.ts', '**/*.test.js', '**/*.spec.ts', '**/*.spec.js', 'src/test/**/*.ts'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
        test: 'readonly',
        suite: 'readonly',

        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        AbortController: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        performance: 'readonly',

        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': typescript,
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      'no-console': 'off',
      'no-undef': 'off',
    },
  },

  {
    files: ['*.d.ts'],
    languageOptions: {
      globals: {
        NotificationOptions: 'readonly',
        Notification: 'readonly',

        Window: 'readonly',
        Document: 'readonly',
        Element: 'readonly',
        Event: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
      'no-undef': 'off',
    },
  },

  prettier,
]
