version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: yun-todo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: yun_todo_db
      POSTGRES_USER: yun_todo_user
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - yun-todo-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U yun_todo_user -d yun_todo_db']
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (可选的数据库管理界面)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: yun-todo-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@yuntodo.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - yun-todo-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  yun-todo-network:
    driver: bridge
